In [1]:
# Course | PG DS- Machine Learning
# Author: Bakul Purohit # Date: 5th June 2021

# Domain : Movie and Entertainment Space
# Project 2: Building user-based recommendation model for Amazon

In [2]:
# Problem Statement Description:

# The dataset provided contains movie reviews given by Amazon customers. Reviews were given between May 1996 and July 2014.

# Data Dictionary
#UserID – 4848 customers who provided a rating for each movie
# Movie 1 to Movie 206 – 206 movies for which ratings are provided by 4848 distinct users

# Data Considerations
# - All the users have not watched all the movies and therefore, all movies are not rated. These missing values are represented by NA.
# - Ratings are on a scale of -1 to 10 where -1 is the least rating and 10 is the best.

# Analysis Task
# - Exploratory Data Analysis:

# Which movies have maximum views/ratings?
# What is the average rating for each movie? Define the top 5 movies with the maximum ratings.
# Define the top 5 movies with the least audience.
# - Recommendation Model: Some of the movies hadn’t been watched and therefore, are not rated by the users. Netflix would like to take this as an opportunity and build a machine learning recommendation algorithm which provides the ratings for each of the users.

# Divide the data into training and test data
# Build a recommendation model on training data
# Make predictions on the test data

In [3]:
import pandas as pd, numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import pairwise_distances

In [4]:
df=pd.read_csv('Amazon - Movies and TV Ratings.csv')

In [5]:
# Data Pre processing-- View the Dataset
df.head()

,user_id,Movie1,Movie2,Movie3,Movie4,Movie5,Movie6,Movie7,Movie8,Movie9,...,Movie197,Movie198,Movie199,Movie200,Movie201,Movie202,Movie203,Movie204,Movie205,Movie206
0,A3R5OBKS7OM2IR,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AH3QC2PC1VTGP,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A3LKP6WPMP9UKX,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AVIY68KEPQ5ZD,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A1CV1WROP5KTTW,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Describe the Dataset
df.describe()

,Movie1,Movie2,Movie3,Movie4,Movie5,Movie6,Movie7,Movie8,Movie9,Movie10,...,Movie197,Movie198,Movie199,Movie200,Movie201,Movie202,Movie203,Movie204,Movie205,Movie206
count,1.0,1.0,1.0,2.0,29.000000,1.0,1.0,1.0,1.0,1.0,...,5.000000,2.0,1.0,8.000000,3.000000,6.000000,1.0,8.000000,35.000000,13.000000
mean,5.0,5.0,2.0,5.0,4.103448,4.0,5.0,5.0,5.0,5.0,...,3.800000,5.0,5.0,4.625000,4.333333,4.333333,3.0,4.375000,4.628571,4.923077
std,NaN,NaN,NaN,0.0,1.496301,NaN,NaN,NaN,NaN,NaN,...,1.643168,0.0,NaN,0.517549,1.154701,1.632993,NaN,1.407886,0.910259,0.277350
min,5.0,5.0,2.0,5.0,1.000000,4.0,5.0,5.0,5.0,5.0,...,1.000000,5.0,5.0,4.000000,3.000000,1.000000,3.0,1.000000,1.000000,4.000000
25%,5.0,5.0,2.0,5.0,4.000000,4.0,5.0,5.0,5.0,5.0,...,4.000000,5.0,5.0,4.000000,4.000000,5.000000,3.0,4.750000,5.000000,5.000000
50%,5.0,5.0,2.0,5.0,5.000000,4.0,5.0,5.0,5.0,5.0,...,4.000000,5.0,5.0,5.000000,5.000000,5.000000,3.0,5.000000,5.000000,5.000000
75%,5.0,5.0,2.0,5.0,5.000000,4.0,5.0,5.0,5.0,5.0,...,5.000000,5.0,5.0,5.000000,5.000000,5.000000,3.0,5.000000,5.000000,5.000000
max,5.0,5.0,2.0,5.0,5.000000,4.0,5.0,5.0,5.0,5.0,...,5.000000,5.0,5.0,5.000000,5.000000,5.000000,3.0,5.000000,5.000000,5.000000

In [7]:
# Exploratory Data Analysis Tasks

# Q 1 Which movie has maximum views/ratings?
# Assumption : A person who has watched has also rated the Movie.
df.describe().T['count'].sort_values(ascending=False).head(1)

Movie127    2313.0
Name: count, dtype: float64

In [8]:
# Ans 1 --> Movie 127 has highest Rating : 2313

In [9]:
# Q 2 What is the average rating for each movie? Define the top 5 movies with the maximum ratings.

df.describe().T['mean'].sort_values(ascending=False).head(5)

Movie1      5.0
Movie55     5.0
Movie131    5.0
Movie132    5.0
Movie133    5.0
Name: mean, dtype: float64

In [10]:
# Ans 2 --> Movies 1,55,131,132 and 133 have highest average Rating = 5

In [11]:
# Q 3 Define the top 5 movies with the least audience.
# Assumption : A person who has watched has also rated the Movie.

df.describe().T['count'].sort_values(ascending=True).head(5)

Movie1      1.0
Movie71     1.0
Movie145    1.0
Movie69     1.0
Movie68     1.0
Name: count, dtype: float64

In [12]:
# Ans 3 -->  Movies 1,71,145,69 and 68 are movies with least audience

In [13]:
# Build a Recommendation Model

In [14]:
# Step 1 : Data Cleaning, Fill NaN values with zeroes
df.fillna(0,inplace=True)

In [15]:
# Step 2 Define Train and Test Data
train_data, test_data = train_test_split(df)
df

,user_id,Movie1,Movie2,Movie3,Movie4,Movie5,Movie6,Movie7,Movie8,Movie9,...,Movie197,Movie198,Movie199,Movie200,Movie201,Movie202,Movie203,Movie204,Movie205,Movie206
0,A3R5OBKS7OM2IR,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AH3QC2PC1VTGP,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,A3LKP6WPMP9UKX,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AVIY68KEPQ5ZD,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,A1CV1WROP5KTTW,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4843,A1IMQ9WMFYKWH5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
4844,A1KLIKPUF5E88I,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
4845,A5HG6WFZLO10D,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
4846,A3UU690TWXCG1X,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
4847,AI4J762YI6S06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0

In [16]:
# Identify the split for Train and Test Data
print('Number of records in train data set ',train_data.shape[0])
print('Number of records in test data set ',test_data.shape[0])

Number of records in train data set  3636
Number of records in test data set  1212

In [17]:
# Step 3 Convert DataFrame into matrix
train_data_mat=train_data.pivot_table(index='user_id')
test_data_mat=test_data.pivot_table(index='user_id')

In [18]:
# Step 4
# Transpose the data
train_data_mat.T

user_id,A0047322388NOTO4N8SKD,A00473363TJ8YSZ3YAGG9,A1004AX2J2HXGL,A100Z2S0880G9A,A102Z4PIK7CYD8,A10367AR7BPFG2,A103HNKB9YAN6P,A103KNDW8GN92L,A107NR3GHQ74T4,A108MGZC58QA8,...,AZDYDCHSLXNAF,AZGQ8DMTSUM0E,AZKPCX1CJ3C2L,AZMYTJWEYTX6O,AZNADO488RR7H,AZQLDLVVX9PE,AZSL7FA9NWYX0,AZT7WWYF4YVJA,AZY4RYP9948K9,AZYJ9TS07B02W
Movie1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Movie10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Movie100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Movie101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Movie102,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Movie95,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Movie96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Movie97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Movie98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Movie99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
# Step 5
# Apply Cosine similarity function
pairwise_distances(train_data_mat,metric='cosine')

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.]])

In [21]:
# Step 6 Push values in Dataframe for Users Data
pd.DataFrame(pairwise_distances(train_data_mat,metric='cosine'),index=train_data_mat.index,columns=train_data_mat.index)

user_id,A0047322388NOTO4N8SKD,A00473363TJ8YSZ3YAGG9,A1004AX2J2HXGL,A100Z2S0880G9A,A102Z4PIK7CYD8,A10367AR7BPFG2,A103HNKB9YAN6P,A103KNDW8GN92L,A107NR3GHQ74T4,A108MGZC58QA8,...,AZDYDCHSLXNAF,AZGQ8DMTSUM0E,AZKPCX1CJ3C2L,AZMYTJWEYTX6O,AZNADO488RR7H,AZQLDLVVX9PE,AZSL7FA9NWYX0,AZT7WWYF4YVJA,AZY4RYP9948K9,AZYJ9TS07B02W
user_id,,,,,,,,,,,,,,,,,,,,,
A0047322388NOTO4N8SKD,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,...,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
A00473363TJ8YSZ3YAGG9,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
A1004AX2J2HXGL,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
A100Z2S0880G9A,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
A102Z4PIK7CYD8,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AZQLDLVVX9PE,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
AZSL7FA9NWYX0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
AZT7WWYF4YVJA,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
AZY4RYP9948K9,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0
AZYJ9TS07B02W,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [22]:
# Step 7 Push values in Dataframe for Movies
pd.DataFrame(pairwise_distances(train_data_mat.T,metric='cosine'),index=train_data_mat.T.index,columns=train_data_mat.T.index)

,Movie1,Movie10,Movie100,Movie101,Movie102,Movie103,Movie104,Movie105,Movie106,Movie107,...,Movie90,Movie91,Movie92,Movie93,Movie94,Movie95,Movie96,Movie97,Movie98,Movie99
Movie1,1.0,1.0,1.0,1.0,1.000000e+00,1.0,1.0,1.0,1.0,1.0,...,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000e+00,1.0,1.0,1.000000e+00
Movie10,1.0,1.0,1.0,1.0,1.000000e+00,1.0,1.0,1.0,1.0,1.0,...,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000e+00,1.0,1.0,1.000000e+00
Movie100,1.0,1.0,1.0,1.0,1.000000e+00,1.0,1.0,1.0,1.0,1.0,...,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000e+00,1.0,1.0,1.000000e+00
Movie101,1.0,1.0,1.0,0.0,1.000000e+00,1.0,1.0,1.0,1.0,1.0,...,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000e+00,1.0,1.0,1.000000e+00
Movie102,1.0,1.0,1.0,1.0,2.220446e-16,1.0,1.0,1.0,1.0,1.0,...,0.584055,1.0,0.899748,1.0,1.0,0.511398,1.000000e+00,1.0,1.0,1.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Movie95,1.0,1.0,1.0,1.0,5.113981e-01,1.0,1.0,1.0,1.0,1.0,...,0.723605,1.0,0.866765,1.0,1.0,0.000000,1.000000e+00,1.0,1.0,1.000000e+00
Movie96,1.0,1.0,1.0,1.0,1.000000e+00,1.0,1.0,1.0,1.0,1.0,...,1.000000,1.0,1.000000,1.0,1.0,1.000000,2.220446e-16,1.0,1.0,1.000000e+00
Movie97,1.0,1.0,1.0,1.0,1.000000e+00,1.0,1.0,1.0,1.0,1.0,...,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000e+00,0.0,1.0,1.000000e+00
Movie98,1.0,1.0,1.0,1.0,1.000000e+00,1.0,1.0,1.0,1.0,1.0,...,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000e+00,1.0,0.0,1.000000e+00
Movie99,1.0,1.0,1.0,1.0,1.000000e+00,1.0,1.0,1.0,1.0,1.0,...,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000e+00,1.0,1.0,2.220446e-16

In [24]:
# Step 8 Derive User and Movie Similarity Scores
user_similarity = pairwise_distances(train_data_mat, metric='cosine')
movie_similarity = pairwise_distances(train_data_mat.T, metric='cosine')

In [25]:
# Step 9. Movie Prediction on Train Data

movie_pred= train_data_mat.dot(movie_similarity) / np.array([np.abs(movie_similarity).sum(axis=1)])
movie_pred

,0,1,2,3,4,5,6,7,8,9,...,196,197,198,199,200,201,202,203,204,205
user_id,,,,,,,,,,,,,,,,,,,,,
A0047322388NOTO4N8SKD,0.024272,0.024272,0.024272,0.024390,0.024537,0.024425,0.024433,0.024517,0.024486,0.024446,...,0.024495,0.024424,0.024464,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
A00473363TJ8YSZ3YAGG9,0.019417,0.019417,0.019417,0.019512,0.019630,0.019306,0.019546,0.019614,0.019588,0.019533,...,0.019596,0.019479,0.019381,0.019512,0.019512,0.019612,0.019512,0.019512,0.019512,0.019736
A1004AX2J2HXGL,0.004854,0.004854,0.004854,0.004878,0.004907,0.004826,0.004887,0.004903,0.004897,0.004883,...,0.004899,0.004870,0.004845,0.004878,0.004878,0.004903,0.004878,0.004878,0.004878,0.004934
A100Z2S0880G9A,0.024272,0.024272,0.024272,0.024390,0.024537,0.024295,0.024433,0.024517,0.024486,0.024446,...,0.024495,0.024424,0.024464,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
A102Z4PIK7CYD8,0.024272,0.024272,0.024272,0.024390,0.024537,0.024425,0.024433,0.024517,0.024486,0.024446,...,0.024495,0.024424,0.024464,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AZQLDLVVX9PE,0.024272,0.024272,0.024272,0.024390,0.024537,0.024132,0.024433,0.024517,0.024486,0.024416,...,0.024495,0.024348,0.024226,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
AZSL7FA9NWYX0,0.024272,0.024272,0.024272,0.024390,0.024537,0.024425,0.024433,0.024517,0.024486,0.024446,...,0.024495,0.024424,0.024464,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
AZT7WWYF4YVJA,0.024272,0.024272,0.024272,0.024390,0.024537,0.024132,0.024433,0.024517,0.024486,0.024416,...,0.024495,0.024348,0.024226,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
AZY4RYP9948K9,0.024272,0.024272,0.024272,0.024390,0.024537,0.024425,0.024433,0.024517,0.024486,0.024446,...,0.024495,0.024424,0.024464,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
AZYJ9TS07B02W,0.014563,0.014563,0.014563,0.014634,0.014722,0.014479,0.014660,0.014710,0.014691,0.014650,...,0.014697,0.014609,0.014536,0.014634,0.014634,0.014709,0.014634,0.014634,0.014634,0.014802

In [26]:
# Step 10 Movie Prediction on Test Data

movie_test_pred= test_data_mat.dot(movie_similarity) / np.array([np.abs(movie_similarity).sum(axis=1)])
movie_test_pred

,0,1,2,3,4,5,6,7,8,9,...,196,197,198,199,200,201,202,203,204,205
user_id,,,,,,,,,,,,,,,,,,,,,
A100CQXJ6D44T9,0.024272,0.024272,0.024272,0.024390,0.024537,0.024425,0.024433,0.024517,0.024486,0.024446,...,0.024495,0.024424,0.024464,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
A1027BL79BSP5P,0.024272,0.024272,0.024272,0.024390,0.024537,0.024132,0.024433,0.024517,0.024486,0.024416,...,0.024495,0.024348,0.024226,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
A109MOLTH35VGS,0.024272,0.024272,0.024272,0.024390,0.024537,0.024425,0.024433,0.024517,0.024486,0.024446,...,0.024495,0.024424,0.024464,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
A10BK26EN1YSZT,0.024272,0.024272,0.024272,0.024390,0.024537,0.024132,0.024433,0.024517,0.024486,0.024416,...,0.024495,0.024348,0.024226,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
A10EH95EUDO9W3,0.014563,0.014563,0.014563,0.014634,0.007529,0.014655,0.014660,0.014710,0.014691,0.014668,...,0.010635,0.014654,0.012723,0.014634,0.014634,0.000000,0.014634,0.014634,0.014634,0.014802
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AZMXYTMWZ26RQ,0.024272,0.024272,0.024272,0.024390,0.024537,0.024132,0.024433,0.024517,0.024486,0.024416,...,0.024495,0.024348,0.024226,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
AZPCHLL1GHUXU,0.024272,0.024272,0.024272,0.024390,0.024537,0.024425,0.024433,0.024517,0.024486,0.024446,...,0.024495,0.024424,0.024464,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
AZR2EXV14JPHN,0.024272,0.024272,0.024272,0.024390,0.024537,0.024425,0.024433,0.024517,0.024486,0.024446,...,0.024495,0.024424,0.024464,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
AZVER2EPLYDZ9,0.024272,0.024272,0.024272,0.024390,0.024537,0.024425,0.024433,0.024517,0.024486,0.024446,...,0.024495,0.024424,0.024464,0.024390,0.024390,0.024515,0.024390,0.024390,0.024390,0.024670
AZZ1KF8RAO1BR,0.009709,0.009709,0.009709,0.009756,0.009815,0.009653,0.009773,0.009807,0.009794,0.009766,...,0.009798,0.009739,0.009690,0.009756,0.009756,0.009806,0.009756,0.009756,0.009756,0.009868